config/routes.rb
# rubocop:disable Lint/MissingCopEnableDirective, Metrics/BlockLength
Rails.application.routes.draw do
  match '/404' => 'errors#not_found', via: :all
  match '422' => 'errors#unprocessable_entity', via: :all
  match '500' => 'errors#internal_server_error', via: :all

  draw(:redirects)
  draw(:admin_v2)
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => 'admin/feature_flags', as: :admin_feature_flags
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
  end

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  unauthenticated do
    root 'static_pages#home'
  end

  authenticated :user do
    root to: redirect('/dashboard'), as: :authenticated_root
  end

  devise_for(
    :users,
    module: 'users',
    controllers: { passwords: 'users/password_resets' },
    path_names: { password: 'password_reset' }
  )

  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    delete '/sign_out' => 'users/sessions#destroy'
    get '/sign_up' => 'users/registrations#new'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
    resources :points, only: %i[index show create]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'team' => 'static_pages#team'
  get 'contributing' => 'static_pages#contributing'
  get 'support_us' => 'static_pages#support_us'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  namespace :guides do
    resources :installations, only: :index
    resource :community, only: :show, controller: 'community' do
      collection do
        get :before_asking
        get :how_to_ask
        get :expectations
        get :rules
      end
    end
  end

  # failure route if github information returns invalid
  get '/auth/failure' => 'users/omniauth_callbacks#failure'
  get 'dashboard' => 'users#show', as: :dashboard

  namespace :users do
    resources :paths, only: :create
    resources :progress, only: :destroy
    resource :profile, only: %i[edit update]
  end

  namespace :lessons do
    resource :preview, only: %i[show create] do
      resource :share, only: %i[create], controller: 'previews/share'
    end
  end

  namespace :courses do
    resources :progress, only: %i[show]
  end

  resources :lessons, only: :show do
    resources :project_submissions, except: :show, controller: 'lessons/project_submissions'
    resource :completion, only: %i[create destroy], controller: 'lessons/completions'
  end

  resources :project_submissions, only: :index do
    resources :flags, only: %i[new create], controller: 'project_submissions/flags'
    resource :like, only: %i[update], controller: 'project_submissions/likes'
  end

  resources :paths, only: %i[index show] do
    resources :courses, only: :show
  end

  resources :notifications, only: %i[index update]
  resource :themes, only: :update
end

app/models/user.rb
class User < ApplicationRecord
  before_create :enroll_in_foundations

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[github google]

  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, length: { in: 2..100 }
  validates :learning_goal, length: { maximum: 1700 }

  has_many :lesson_completions, dependent: :destroy
  has_many :completed_lessons, through: :lesson_completions, source: :lesson
  has_many :project_submissions, dependent: :destroy
  has_many :user_providers, dependent: :destroy
  has_many :flags, foreign_key: :flagger_id, dependent: :destroy, inverse_of: :flagger
  has_many :notifications, as: :recipient, dependent: :destroy
  has_many :announcements, dependent: nil
  has_many :likes, dependent: :destroy
  belongs_to :path, optional: true

  def progress_for(course)
    @progress ||= Hash.new { |hash, c| hash[c] = CourseProgress.new(c, self) }
    @progress[course]
  end

  def completed?(lesson)
    completed_lessons.pluck(:id).include?(lesson.id)
  end

  def latest_completed_lesson
    return if last_lesson_completed.nil?

    Lesson.find(last_lesson_completed.lesson_id)
  end

  def lesson_completions_for_course(course)
    lesson_completions.where(course_id: course.id)
  end

  def active_for_authentication?
    super && !banned?
  end

  def inactive_message
    banned? ? :banned : super
  end

  def dismissed_flags
    flags.where(taken_action: :dismiss)
  end

  def started_course?(course)
    lesson_completions.exists?(course_id: course.id)
  end

  def on_path?(path)
    self.path == path
  end

  private

  def last_lesson_completed
    lesson_completions.order(created_at: :asc).last
  end

  def enroll_in_foundations
    default_path = Path.default_path

    self.path_id = default_path.id if default_path.present?
  end
end

app/models/users/theme.rb
module Users
  class Theme
    include Comparable

    DEFAULT_THEMES = [
      %w[light sun],
      %w[dark moon]
    ].freeze

    def self.default_themes
      DEFAULT_THEMES.map { |name, icon| new(name:, icon:) }
    end

    def self.exists?(theme)
      default_themes.map(&:name).include?(theme)
    end

    def self.for(value)
      default_themes.find { |theme| theme.name == value }
    end

    attr_reader :name, :icon

    def initialize(name:, icon:)
      @name = name
      @icon = icon
    end

    def <=>(other)
      name <=> other.name
    end

    def to_s
      name
    end

    def dark_mode?
      name == 'dark'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = UserProvider.find_user(auth)

    update_users_avatar if avatar_needs_updated?

    if @user.persisted?
      @user.remember_me = true
      sign_in_and_redirect @user
    else
      session['devise.github_data'] = auth
      redirect_to new_user_registration_url
    end
  end
  alias google github

  def failure
    redirect_to new_user_session_path, alert: 'Authentication failed'
  end

  private

  def update_users_avatar
    @user.update!(avatar: avatar_from_provider)
  end

  def avatar_needs_updated?
    avatar_from_provider != @user.avatar
  end

  def avatar_from_provider
    @avatar_from_provider ||= auth.info.image
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < Devise::PasswordsController
end

app/controllers/users/paths_controller.rb
module Users
  class PathsController < ApplicationController
    before_action :authenticate_user!
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    def create
      if current_user.update(path:)
        redirect_to path, notice: "You have selected the #{path.title} path"
      else
        redirect_back(fallback_location: paths_url, alert: "Unable to select the #{path.title} path")
      end
    end

    private

    def path
      Path.find(params[:path_id])
    end

    def record_not_found
      redirect_to paths_url, alert: 'Path not found'
    end
  end
end

app/controllers/users/profiles_controller.rb
module Users
  class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def edit; end

    def update
      if current_user.update(user_params)
        redirect_to edit_users_profile_path, notice: 'Your account has been updated'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def user_params
      params.require(:user).permit(:email, :username, :learning_goal)
    end
  end
end

app/controllers/users/progress_controller.rb
module Users
  class ProgressController < ApplicationController
    before_action :authenticate_user!

    def destroy
      result = Users::ResetProgress.call(current_user)
      if result.success?
        redirect_to edit_users_profile_path, notice: 'Success: Your progress has been reset.'
      else
        redirect_to edit_users_profile_path, notice: 'Failure: Unable to reset your progress.'
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super

    if resource.persisted? && ENV['STAGING'].nil?
      UserMailer.send_welcome_email_to(resource).deliver_later
    end
  end

  protected

  def after_sign_up_path_for(_resource)
    dashboard_path
  end

  def after_inactive_sign_up_path_for(_resource)
    dashboard_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @courses = current_user.path.courses
    @project_submissions = current_user.project_submissions.includes(:lesson).order(created_at: :desc)
  end
end

app/views/users/profiles/edit.html.erb
<%= title('Settings') %>

<div class="page-container">
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
    <aside class="py-6 px-2 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3">
      <%= render VerticalNavigation::ContainerComponent.new do |c| %>
        <% c.with_links(
             [
               { name: 'Profile', href: edit_users_profile_path, icon_path: 'user-circle.svg' },
               { name: 'Password', href: edit_user_registration_path, icon_path: 'key.svg' },
             ]
           ) %>
      <% end %>
    </aside>

    <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">

      <%= form_with model: current_user, url: users_profile_path, builder: TailwindFormBuilder do |form| %>
        <%= render CardComponent.new do |card| %>
          <% card.with_header do %>
              <h3 class="text-xl leading-6 font-medium text-gray-900 dark:text-gray-200">Profile</h3>
              <p class="text-sm mt-2 text-gray-500 dark:text-gray-400">Profile information will be displayed on your dashboard.</p>
          <% end %>
          <% card.with_body do %>
            <div class="grid grid-cols-6 gap-6">

              <div class="col-span-6 sm:col-span-3">
                <%= form.label :username %>
                <%= form.text_field :username, class: 'dark-form-input', data: { test_id: 'username-field' } %>
              </div>

              <div class="col-span-6 sm:col-span-4">
                <%= form.label :email %>
                <%= form.email_field :email, class: 'dark-form-input', data: { test_id: 'email-field' } %>
              </div>

              <div class="col-span-6 sm:col-span-6">
                <%= form.label :learning_goal %>
                <%= form.text_area :learning_goal, class: 'dark-form-input', placeholder: 'I wanna be the very best...', rows: 4, data: { test_id: 'learning-goal-field' }, autofocus: params[:learning_goal].present? %>
              </div>

              <div class="col-span-6">
                <%= form.label :avatar %>
                <div class="flex items-center">
                  <%= render User::AvatarComponent.new(current_user:, classes: 'w-16') %>
                </div>
                  <p class="text-sm text-gray-500 mt-2 dark:text-gray-400">Avatar can be grabbed from Github or Google when signing in with those services.</p>
              </div>
            </div>
          <% end %>
          <% card.with_footer(classes: 'px-4 py-3 pt-3 bg-gray-50 text-right sm:px-6 dark:bg-gray-700/40 rounded-b-lg') do %>
            <%= form.submit 'Save', class: 'button button--primary py-2 px-4', data: { test_id: 'save-profile-btn', disable_with: false } %>
          <% end %>
        <% end %>
      <% end %>

      <%= render CardComponent.new do |card| %>
        <% card.with_header do %>
          <h3 class="text-xl leading-6 font-medium text-gray-900 dark:text-gray-200">Danger Zone</h3>
            <p class="text-sm mt-2 text-gray-500 dark:text-gray-400">Careful, these actions can not be undone.</p>
        <% end %>
        <% card.with_body do %>
          <div class="inline-flex flex-col space-y-5">
            <%= link_to users_progress_path(current_user), class: 'button button--secondary px-3 py-2 text-sm', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?', test_id: 'user-reset-progress-link' } do %>
              <%= inline_svg_tag 'icons/refresh.svg', class: '-ml-0.5 mr-2 h-4 w-4 text-red-700 dark:text-red-500', aria: true, title: 'Reset icon' %>
              Reset progress
            <% end %>
            <%= link_to registration_path(current_user), class: 'button button--secondary px-3 py-2 text-sm', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?', test_id: 'user-account-delete-link' } do %>
              <%= inline_svg_tag 'icons/trash.svg', class: '-ml-0.5 mr-2 h-4 w-4 text-red-700 dark:text-red-500', aria: true, title: 'Trash can icon' %>
              Delete account
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>