config/routes.rb
# rubocop:disable Lint/MissingCopEnableDirective, Metrics/BlockLength
Rails.application.routes.draw do
  match '/404' => 'errors#not_found', via: :all
  match '422' => 'errors#unprocessable_entity', via: :all
  match '500' => 'errors#internal_server_error', via: :all

  draw(:redirects)
  draw(:admin_v2)
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => 'admin/feature_flags', as: :admin_feature_flags
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
  end

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  unauthenticated do
    root 'static_pages#home'
  end

  authenticated :user do
    root to: redirect('/dashboard'), as: :authenticated_root
  end

  devise_for(
    :users,
    module: 'users',
    controllers: { passwords: 'users/password_resets' },
    path_names: { password: 'password_reset' }
  )

  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    delete '/sign_out' => 'users/sessions#destroy'
    get '/sign_up' => 'users/registrations#new'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
    resources :points, only: %i[index show create]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'team' => 'static_pages#team'
  get 'contributing' => 'static_pages#contributing'
  get 'support_us' => 'static_pages#support_us'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  namespace :guides do
    resources :installations, only: :index
    resource :community, only: :show, controller: 'community' do
      collection do
        get :before_asking
        get :how_to_ask
        get :expectations
        get :rules
      end
    end
  end

  # failure route if github information returns invalid
  get '/auth/failure' => 'users/omniauth_callbacks#failure'
  get 'dashboard' => 'users#show', as: :dashboard

  namespace :users do
    resources :paths, only: :create
    resources :progress, only: :destroy
    resource :profile, only: %i[edit update]
  end

  namespace :lessons do
    resource :preview, only: %i[show create] do
      resource :share, only: %i[create], controller: 'previews/share'
    end
  end

  namespace :courses do
    resources :progress, only: %i[show]
  end

  resources :lessons, only: :show do
    resources :project_submissions, except: :show, controller: 'lessons/project_submissions'
    resource :completion, only: %i[create destroy], controller: 'lessons/completions'
  end

  resources :project_submissions, only: :index do
    resources :flags, only: %i[new create], controller: 'project_submissions/flags'
    resource :like, only: %i[update], controller: 'project_submissions/likes'
  end

  resources :paths, only: %i[index show] do
    resources :courses, only: :show
  end

  resources :notifications, only: %i[index update]
  resource :themes, only: :update
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @landing_page = true
    @success_stories = SuccessStory.limit(4)
    @courses = Course.badges
  end

  def about; end

  def faq; end

  def team; end

  def terms_of_use; end

  def privacy_policy; end

  def success_stories
    @success_stories = SuccessStory.all
  end
end

app/views/static_pages/about.html.erb
<%= title('About') %>

<div class="page-container">
  <div class="grid grid-cols-12">
    <div class="col-span-12 md:col-start-3 md:col-span-8">
      <div class="pb-20">
        <h1 class="page-heading-title">About The Odin Project</h1>
        <p class="prose max-w-none prose-gray dark:prose-invert">
          The Odin Project is one of those "What I wish I had when I was learning" resources. Not everyone has access to a computer science education or the funds to attend an intensive coding school and neither of those is right for everyone anyway.  This project is designed to fill in the gap for people who are trying to hack it on their own but still want a high quality education.
        </p>
      </div>

      <h2 class="text-center text-gray-700 dark:text-gray-300 text-2xl mb-12">What you can expect at The Odin Project</h2>
      <%= render(AboutPage::BeliefComponent.with_collection(t('.beliefs'))) %>
    </div>
  </div>
</div>

<%= render 'static_pages/about/overview' %>

<div class="page-container" id="contact-us">
  <div class="flex p-8 items-center flex-col md:flex-row">
    <div class="flex-1 flex justify-center">
      <%= inline_svg 'about_page/odin-mascot.svg', alt: 'Odin Mascot', class: 'h-72' %>
    </div>

    <div class="flex-1 mt-8 md:mt-0 text-center">
      <h2 class="mb-4 font-bold text-2xl">Want to contact us?</h2>

      <p class="pb-8 max-w-md mx-auto dark:text-gray-400 text-gray-500">
        Connect with our friendly community on discord, a chat and networking platform or <a href="mailto:theodinprojectcontact@gmail.com" class="underline hover:no-underline text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300">send us an email</a>.
      </p>

      <%= link_to 'Chat on Discord', ODIN_CHAT_URL, class: 'button button--secondary px-4', target: '_blank', rel: 'noreferrer' %>
    </div>
  </div>
</div>

<div class="bg-gray-50 dark:bg-gray-900 my-16">
  <div class="max-w-2xl mx-auto text-lg text-center">
    If you want to give back to our community, you can do so by contributing to our open source projects, or by supporting us financially.
    <div class="flex justify-center space-x-4 mt-4 mb-8">
      <a href="/contributing" class="button button--primary">Contribute</a>
      <a href="/support_us" class="button button--primary">Donate</a>
    </div>
  </div>
</div>

app/views/static_pages/contributing.html.erb
<%= title('Contributing') %>

<section class='page-container'>
  <div class='grid grid-cols-12'>
    <div class='col-span-12 md:col-start-3 md:col-span-8 space-y-8'>
      <div class='text-center'>
        <h1 class='page-heading-title'>How to Contribute</h1>
        <p class='max-w-prose mx-auto prose prose-gray dark:prose-invert text-gray-500 dark:text-gray-400'>
          The Odin Project is an Open Source project, built and maintained by <%= link_to 'volunteers', team_path %> who dedicate their time
          and skills to making The Odin Project one of the best free education platforms on the web. We are always
          working on projects to improve Odin and are always looking for people who want to join our growing team
          of maintainers.
        </p>
        <p class='max-w-prose mx-auto mt-4 prose prose-gray text-sm italic dark:prose-invert text-gray-500 dark:text-gray-400'>
          If you are interested in supporting us financially, you can learn about that on <%= link_to 'our support page.', support_us_path %>
        </p>
      </div>

      <%= render 'static_pages/contributing/contributing_options' %>
    </div>
  </div>
</section>

<section class='bg-gray-100 dark:bg-gray-800'>
  <div class='page-container'>
    <div class='grid grid-cols-12'>
      <div class='col-span-12 md:col-start-3 md:col-span-8'>
        <h2 class='font-bold text-center mb-16 text-2xl'>Why you should get involved</h2>
        <%= render(AboutPage::BeliefComponent.with_collection(t('.benefits'))) %>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/faq.html.erb
<%= title('FAQ') %>

<div class="page-container">
  <h1 class="page-heading-title">Frequently Asked Questions</h1>
  <div class="max-w-7xl mx-auto py-12 px-4 sm:py-16 sm:px-6 lg:px-8">
    <div class="max-w-3xl mx-auto divide-y-2 divide-gray-200">
      <dl class="space-y-6 divide-y divide-gray-200 dark:divide-gray-700">
        <% t('.items').each do |item| %>
          <%= render Faq::ItemComponent.new(item:) %>
        <% end %>
      </dl>
    </div>
  </div>

  <%= render(
        'shared/bottom_cta',
        button: chat_button,
        heading: 'Have a question?',
        sub_heading: 'Chat with our friendly Odin community in our Discord server!'
      ) %>
</div>

app/views/static_pages/home.html.erb
<div id="home-page">
  <div class="w-full text-center bg-white dark:bg-gray-900 text-">
    <header class="page-container pb-4">
      <div class="max-w-4xl mx-auto sm:pt-16">
        <h1 class="text-4xl sm:text-6xl text-gray-700 dark:text-gray-200 font-medium mx-auto pb-6 tracking-tighter">
          Your <span class="text-gold-600 dark:text-gold-600">Career in Web Development</span> <span class="block font-medium">Starts Here</span>
        </h1>
        <div class="text-gray-600 dark:text-gray-300/80 pb-8 max-w-xl mx-auto">
          <p class="mb-4 text-xl text-gray-500 dark:text-gray-400">Our full stack curriculum is free and supported by a passionate open source community.</p>
        </div>
      </div>

      <%= link_to 'View Full Curriculum', paths_url, class: 'button button--secondary text-base' %>
    </header>
    <%= image_tag 'home-isometric.svg', alt: 'home-page-banner', class: 'w-full h-full' %>
  </div>

  <%= render 'static_pages/home/how_it_works' %>

  <%= render 'static_pages/home/curriculum', courses: @courses %>

  <%= render 'static_pages/home/success_stories', cache: true %>

  <% if Rails.env.test? && Feature.enabled?(:test_feature, current_user) %>
    test feature is enabled
  <% end %>
</div>

app/views/static_pages/privacy_policy.html.erb
<%= title('Privacy Policy') %>

<div class="page-container">
  <h1 class="page-heading-title">Privacy Policy</h1>

  <%= render ContentContainerComponent.new do %>
    <p>At The Odin Project, accessible from <%= link_to 'https://www.theodinproject.com/', home_path %>, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by The Odin Project and how we use it.</p>
    <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to <%= mail_to CONTACT_EMAIL, 'contact us' %>.</p>

    <h3>General Data Protection Regulation (GDPR)</h3>
    <p>We are a Data Controller of your information.</p>

    <p>The Odin Project legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Information we collect and the specific context in which we collect the information:</p>
    <ul>
      <li>The Odin Project needs to perform a contract with you</li>
      <li>You have given The Odin Project permission to do so</li>
      <li>Processing your personal information is in The Odin Project legitimate interests</li>
      <li>The Odin Project needs to comply with the law</li>
    </ul>

    <p>The Odin Project will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.</p>
    <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. If you wish to be informed what Personal Information we hold about you and if you want it to be removed from our systems, please <%= mail_to CONTACT_EMAIL, 'contact us' %>.</p>

    <p>In certain circumstances, you have the following data protection rights:</p>

    <ul>
      <li>The right to access, update or to delete the information we have on you.</li>
      <li>The right of rectification.</li>
      <li>The right to object.</li>
      <li>The right of restriction.</li>
      <li>The right to data portability.</li>
      <li>The right to withdraw consent.</li>
    </ul>

    <h3>Log Files</h3>
    <p>The Odin Project follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and is a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

    <h3>Cookies and Web Beacons</h3>
    <p>Like any other website, The Odin Project uses "cookies". These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

    <h3>Privacy Policies</h3>
    <p>You may consult this list to find the Privacy Policy for each of the advertising partners of The Odin Project.</p>
    <p>Third-parties, those providing ad servers or ad networks, or other services/technologies, may use technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements/services and links that appear on The Odin Project, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising/service campaigns and/or to personalize the advertising/service content that you see on websites that you visit.</p>
    <p>Note that The Odin Project has no access to or control over these cookies that are used by third-party advertisers.</p>

    <h3>Third Party Privacy Policies</h3>
    <p>The Odin Project's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.</p>
    <p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>

    <h3>Children's Information</h3>
    <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>
    <p>The Odin Project does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to <%= mail_to CONTACT_EMAIL, 'contact us' %> immediately and we will do our best efforts to promptly remove such information from our records.</p>

    <h3>Online Privacy Policy Only</h3>
    <p>Our Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in The Odin Project. This policy is not applicable to any information collected offline or via channels other than this website.</p>

    <h3>Consent</h3>
    <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>
  <% end %>
</div>

app/views/static_pages/success_stories.html.erb
<%= title('Success Stories') %>

<div class="page-container">
  <h1 class="page-heading-title">Success Stories</h1>

  <div class="max-w-5xl mx-auto">

    <% @success_stories.each do |story| %>
      <%= render CardComponent.new(classes: 'mb-10', id: dom_id(story)) do |card| %>
        <% card.with_header do %>
          <div class="flex flex-col sm:flex-row items-center space-y-2 sm:space-y-0 sm:space-x-4">
            <div class="w-20 h-20 rounded-full overflow-hidden">
              <%= image_tag "success_stories/#{story.avatar_path_name}", alt: '', class: 'w-full shadow-inner aspect-auto' %>
            </div>
            <div class="flex flex-col text-center sm:text-left">
              <div class="flex flex-row gap-2 items-center">
                <% if story.social_media_link.present? %>
                  <p class="font-bold"><%= link_to story.student_name, story.social_media_link, class: 'underline hover:no-underline text-gray-600 hover:text-gray-800 dark:text-gray-200 dark:hover:text-gray-300' %></p>
                  <%= link_to story.social_media_link do %>
                    <%= inline_svg_tag(
                          'icons/link.svg',
                          class: 'h-4 w-4 text-gray-400 dark:text-gray-500 hover:text-gray-800 dark:hover:text-gray-300',
                          title: 'See user site',
                          aria: true,
                          desc: "A link that goes to the user's personal site.",
                          data: { test_id: "social_media_#{story.avatar_path_name}" }
                        ) %>
                  <% end %>
                <% else %>
                  <p class='font-bold text-gray-600 dark:text-gray-200'>
                    <%= story.student_name %>
                  </p>
                <% end %>
              </div>
              <p class="text-gray-500 dark:text-gray-400"><%= story.job_title %></p>
            </div>
          </div>
        <% end %>
        <% card.with_body do %>
          <div class="prose prose-gray dark:prose-invert max-w-none dark:antialiased"><%= story.story_content.html_safe %></div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= render 'shared/bottom_cta',
    button: sign_up_or_view_curriculum_button,
    heading: 'Start learning for free now!' %>
</div>

app/views/static_pages/support_us.html.erb
<%= title('Support the Project') %>

<div id="support-us">
  <section class='page-container'>
    <div class='grid grid-cols-12'>
      <div class='col-span-12 md:col-start-3 md:col-span-8 space-y-8'>
        <div class='text-center'>
          <h1 class='page-heading-title'>Support the Project</h1>
          <p class='max-w-prose mx-auto prose prose-gray dark:prose-invert text-gray-600 dark:text-gray-300'>
            From the very beginning, The Odin Project has been committed to providing a world-class and completely free coding curriculum for anyone and everyone eager to learn.
            With your generous donations, we can continue to inspire thousands of aspiring developers, irrespective of their background or financial status.
          </p>
        </div>
      </div>
    </div>

    <div class="mt-8 text-center">
      <%= link_to 'Donate now!', 'https://opencollective.com/theodinproject/donate?amount=5', class: 'button button--primary text-base px-12 py-4', target: '_blank' %>
    </div>
    <%# <script src='https://opencollective.com/theodinproject/banner.js?style={"h2":{"color":"rgb(112, 112, 128)"}}'></script> %>
  </section>

  <section class='bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400'>
    <div class='page-container'>
      <div class='grid grid-cols-12'>
        <div class='col-span-12 md:col-start-3 md:col-span-8 prose dark:prose-invert max-w-none prose-a:text-blue-800 dark:prose-a:text-blue-300'>
          <h2 class="text-center mb-16">Frequently Asked Questions</h2>

          <h3>How will my money be used?</h3>
          <p>Your money will be used to pay for the costs of running The Odin Project. This includes paying for the servers that host the website, the domain name, and any other costs associated with running the project. Your money does <i>not</i> go towards paying the maintainers. All of our expenses are documented directly on the <%= link_to 'Open Collective website.', 'https://opencollective.com/theodinproject', target: '_blank' %></p>

          <h3>How can I donate?</h3>
          <p>You can donate via <%= link_to 'Open Collective', 'https://opencollective.com/theodinproject', target: '_blank' %>, by setting up a recurring donation or with a one time payment.</p>

          <h3>What form of payments can I use?</h3>
          <p>You can usually pay by credit card through our Open Collective page. They also offer bank transfer, Paypal, or other means in addition to or instead of credit card payments. When you go through the contribution flow, you'll see all the available payment methods.</p>

          <h3>What happens if you receive more donations than needed?</h3>
          <p>Any extra money that we receive will be used to improve The Odin Project, or will be saved for future needs. This includes paying for new features, paying for new servers, and paying for any other costs associated with running the project.</p>

          <h3>How do I cancel my recurring donation?</h3>
          <p>You can cancel your recurring donation at any time through your Open Collective profile.</p>

          <h3>What are the benefits of donating?</h3>
          <p>Your donation helps us continue to provide a world-class and completely free coding curriculum for anyone and everyone eager to learn. We believe that this material should be available for free to anyone that needs it, and donations from those that have the means to contribute help keep it available for everyone!</p>
          <p>In additon to the above, donors get a special 'backer' role in our discord server as a small bit of recognition.</p>

          <h3>How do I get the 'backer' role on Discord?</h3>
          <p>
            Use the <code>/opencollective</code> command in our discord server to verify your Open Collective account. You will then be automatically given the 'backer' role.
            You will be prompted to provide your Open Collective username, which is found in the URL of your Open Collective profile. For example, if your profile URL is <code>https://opencollective.com/rick-astley</code> your username is <code>rick-astley</code>.
          </p>
          <p>If you want to remove the role for any reason, contact staff on discord through ModMail.</p>

          <h3>Do users with the 'backer' role get any exclusive benefits?</h3>
          <p>No. The role is just a way for us to show our appreciation for your support.</p>

          <h3>Does becoming a donor mean I get priority support in the chat?</h3>
          <p>No. We feel strongly that everyone should be treated equally in our community, regardless of whether or not they are a donor.</p>

          <h3>I cannot afford to donate right now. What are some other ways I can help The Odin Project?</h3>
          <p>You can help us by <%= link_to 'contributing to our open source projects.', contributing_path, target: '_blank' %> You can also help us by spreading the word about The Odin Project. Tell your friends, family, and coworkers about us. Share our content on social media. The more people that know about us, the more people we can help.</p>

          <h3>What ever happened to Thinkful? Viking Code School?</h3>
          <p>When The Odin Project was created by Eric Trautman in 2013, it was primarily funded by Eric's other project, the for-profit Viking Code School. Eric wanted Odin to be free, and kept it that way by placing a small ad for Viking Code School on the website.</p>
          <p>In late 2017, Viking Code School was acquired by Thinkful. As a part of that acquisition, Thinkful agreed to continue funding The Odin Project, in return for an ad on The Odin Project website.</p>
          <p>In 2019, Thinkful was acquired by Chegg. Chegg was nothing but supportive, and continued funding us the entire time. However we began to feel that it might be in our best interest to become self-funding, to avoid the risk of being acquired by a company that might not be as supportive.</p>
          <p>In 2023, we decided to begin the process of parting ways with Chegg, and become self-funding. We are now funded entirely by donations.</p>

          <h3>I still have questions. How can I contact you?</h3>
          <p>You can contact us through modmail on our discord server, or through email.  See our <%= link_to 'contact us', about_path(anchor: 'contact-us'), target: '_blank' %> page for details.</p>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/static_pages/team.html.erb
<%= title('Team') %>

<div class="page-container">
  <div>
    <h1 class="page-heading-title pb-4">Meet The Team</h1>
    <p class="pb-4 text-center text-sm sm:text-base mx-auto text-gray-500 dark:text-gray-400">
      The Odin project is run by a group of dedicated volunteers from around the world.
    </p>
    <%= render Team::NavigationComponent.new(
          roles: [
            { name: 'Core', url: '#core' },
            { name: 'Maintainers', url: '#maintainers' },
            { name: 'Moderators', url: '#moderators' },
            { name: 'Alumni', url: '#alumni' }
          ]
        ) %>
  </div>

  <div class="max-w-7xl mx-auto pt-10 px-4 sm:pt-12 sm:px-6 lg:px-8">
    <div class="mt-10 space-y-16">
      <%= render 'static_pages/team/role', role: 'core', title: 'Core' %>
      <%= render 'static_pages/team/role', role: 'maintainers', title: 'Maintainers' %>
      <%= render 'static_pages/team/role', role: 'moderators', title: 'Moderators' %>
      <%= render 'static_pages/team/alumni', role: 'alumni' %>
    </div>

      <p class="text-center">
        <%= render 'shared/bottom_cta',
          button: contribute_button,
          heading: 'To all our contributors ❤️',
          sub_heading: "We've had thousands of contributors outside of the official teams. To them, we extend a special thanks. Each and every contribution has played an important role in improving The Odin Project for the benefit of all learners." %>
      </p>
  </div>
</div>