config/routes.rb
# rubocop:disable Lint/MissingCopEnableDirective, Metrics/BlockLength
Rails.application.routes.draw do
  match '/404' => 'errors#not_found', via: :all
  match '422' => 'errors#unprocessable_entity', via: :all
  match '500' => 'errors#internal_server_error', via: :all

  draw(:redirects)
  draw(:admin_v2)
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => 'admin/feature_flags', as: :admin_feature_flags
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
  end

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  unauthenticated do
    root 'static_pages#home'
  end

  authenticated :user do
    root to: redirect('/dashboard'), as: :authenticated_root
  end

  devise_for(
    :users,
    module: 'users',
    controllers: { passwords: 'users/password_resets' },
    path_names: { password: 'password_reset' }
  )

  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    delete '/sign_out' => 'users/sessions#destroy'
    get '/sign_up' => 'users/registrations#new'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
    resources :points, only: %i[index show create]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'team' => 'static_pages#team'
  get 'contributing' => 'static_pages#contributing'
  get 'support_us' => 'static_pages#support_us'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  namespace :guides do
    resources :installations, only: :index
    resource :community, only: :show, controller: 'community' do
      collection do
        get :before_asking
        get :how_to_ask
        get :expectations
        get :rules
      end
    end
  end

  # failure route if github information returns invalid
  get '/auth/failure' => 'users/omniauth_callbacks#failure'
  get 'dashboard' => 'users#show', as: :dashboard

  namespace :users do
    resources :paths, only: :create
    resources :progress, only: :destroy
    resource :profile, only: %i[edit update]
  end

  namespace :lessons do
    resource :preview, only: %i[show create] do
      resource :share, only: %i[create], controller: 'previews/share'
    end
  end

  namespace :courses do
    resources :progress, only: %i[show]
  end

  resources :lessons, only: :show do
    resources :project_submissions, except: :show, controller: 'lessons/project_submissions'
    resource :completion, only: %i[create destroy], controller: 'lessons/completions'
  end

  resources :project_submissions, only: :index do
    resources :flags, only: %i[new create], controller: 'project_submissions/flags'
    resource :like, only: %i[update], controller: 'project_submissions/likes'
  end

  resources :paths, only: %i[index show] do
    resources :courses, only: :show
  end

  resources :notifications, only: %i[index update]
  resource :themes, only: :update
end

app/views/shared/_analytics.html.erb
<% if Rails.env.production? %>
  <script defer data-turbo-eval="false" src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "031c5e68316544eb9f1a2118163c1cfd"}'>
  </script>
<% end %>

app/views/shared/_bottom_cta.html.erb
<div class="max-w-4xl py-20 mx-auto text-center">
  <h2 class="mb-4 text-2xl font-light leading-10 text-gray-600 dark:text-gray-200"><%= heading %></h2>
  <% if local_assigns[:sub_heading].present? %>
  <p class="mb-10 font-normal text-gray-500 dark:text-gray-400"><%= sub_heading %></p>
  <% end %>
  <%= button %>
</div>

app/views/shared/_flash.html.erb
<div class="flex flex-col items-end space-y-4">
  <div class="fixed top-10 z-40 mr-8">
    <% flash.each do |type, message| %>
      <%= render Alerts::FlashComponent.new(type:, message:) %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<% unless current_page?(support_us_path) || current_page?(about_path) %>
  <div class="bg-gray-100 dark:bg-gray-800/30">
    <div class="mx-auto max-w-xl px-8 py-20 xs:pt-24 lg:px-8 text-center">
      <div>
        <div class="flex-1 mb-6">
          <h1 class="text-3xl mb-4 font-semibold text-gray-800 dark:text-gray-200">Support us!</h1>
          <h2 class="text-sm text-gray-500 dark:text-gray-400">The Odin Project is funded by the community. Join us in empowering learners around the globe by supporting The Odin Project!</h2>
        </div>
        <div class="mt-4 flex justify-center space-x-4">
          <%= link_to 'Learn more', support_us_path, class: 'button button--secondary' %>
          <%= link_to 'https://opencollective.com/theodinproject/donate?amount=5', class: 'button button--primary relative', target: '_blank' do %>
            <span class="mr-4">Donate now</span>
            <%= inline_svg_tag 'icons/arrow-right.svg', class: 'absolute right-3 h-4 w-4 ml-2', aria: false %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<footer class="bg-white dark:bg-gray-900" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="mx-auto max-w-7xl px-6 pb-8 pt-8 sm:pt-12 lg:px-8">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">

      <div class="space-y-6">
        <%= render LogoComponent.new(classes: 'block h-12 w-auto') %>
        <p class="text-sm leading-6 text-gray-600 dark:text-gray-300">
          High quality coding education maintained by an open source community.
        </p>

        <div class="flex space-x-6">
          <%= link_to 'https://github.com/TheOdinProject', class: 'text-gray-400 hover:text-gray-500 dark:text-gray-500 dark:hover:text-gray-400' do %>
            <span class="sr-only">GitHub</span>
            <%= inline_svg_tag 'socials/github.svg', class: 'h-6 w-6 fill-current hover:fill-black dark:hover:fill-white transition duration-500', aria: true, title: 'GitHub', desc: 'GitHub logo' %>
          <% end %>

          <%= link_to ODIN_CHAT_URL, class: 'text-gray-400 hover:text-gray-500 dark:text-gray-500 dark:hover:text-gray-400' do %>
            <span class="sr-only">Discord</span>
            <%= inline_svg_tag 'socials/discord.svg', class: 'h-6 w-6 fill-current hover:fill-[#7289d9] transition duration-500', aria: true, title: 'Discord', desc: 'Discord logo' %>
          <% end %>

          <%= link_to 'https://www.facebook.com/theodinproject/', class: 'text-gray-400 hover:text-gray-500 dark:text-gray-500 dark:hover:text-gray-400' do %>
            <span class="sr-only">Facebook</span>
            <%= inline_svg_tag 'socials/facebook.svg', class: 'h-6 w-6 fill-current hover:fill-[#4267B2] transition duration-500', aria: true, title: 'Facebook', desc: 'Facebook logo' %>
          <% end %>

          <%= link_to 'https://twitter.com/TheOdinProject', class: 'text-gray-400 hover:text-gray-500 dark:text-gray-500 dark:hover:text-gray-400' do %>
            <span class="sr-only">Twitter</span>
            <%= inline_svg_tag 'socials/twitter.svg', class: 'h-6 w-6 fill-current hover:fill-[#1DA1F2] transition duration-500', aria: true, title: 'Twitter', desc: 'Twitter logo' %>
          <% end %>
        </div>
      </div>

      <div class="mt-16 grid grid-cols-2 gap-8 xl:col-span-2 xl:mt-0">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold leading-6 text-gray-900 dark:text-white">About us</h3>
            <ul role="list" class="mt-4 space-y-3">
              <li><%= link_to 'About', about_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
              <li><%= link_to 'Team', team_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
              <li><%= link_to 'Blog', blog_path, target: '_blank', rel: 'noreferrer', class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
              <li><%= link_to 'Success Stories', success_stories_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
            </ul>
          </div>

          <div class="mt-10 md:mt-0">
            <h3 class="text-sm font-semibold leading-6 text-gray-900 dark:text-white">Support</h3>
            <ul role="list" class="mt-4 space-y-3">
              <li><%= link_to 'FAQ', faq_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white', data: { test_id: 'faq-link' } %></li>
              <li><%= link_to 'Contribute', contributing_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
              <li><%= link_to 'Contact us', about_path(anchor: 'contact-us'), class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>

            </ul>
          </div>
        </div>

        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold leading-6 text-gray-900 dark:text-white">Guides</h3>
            <ul role="list" class="mt-4 space-y-3">
              <li><%= link_to 'Community guides', guides_community_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white', data: { test_id: 'faq-link' } %></li>
              <li><%= link_to 'Installation guides', guides_installations_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white', data: { test_id: 'faq-link' } %></li>
            </ul>
          </div>

          <div class="mt-10 md:mt-0">
            <h3 class="text-sm font-semibold leading-6 text-gray-900 dark:text-white">Legal</h3>
            <ul role="list" class="mt-4 space-y-3">
              <li><%= link_to 'Terms', terms_of_use_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
              <li><%= link_to 'Privacy', privacy_policy_path, class: 'text-sm leading-6 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white' %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-16 border-t border-gray-900/10 dark:border-white/10 pt-8 sm:mt-20 lg:mt-24">
      <p class="text-xs leading-5 text-gray-600 dark:text-gray-300">&copy; <%= Time.current.year %> The Odin Project. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<%= render 'shared/off_canvas_menu' %>
<nav class="border-gray-200 bg-white dark:bg-gray-900 dark:border-gray-800 <%= 'border-b' unless @landing_page %>">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2">
    <div class="flex justify-between">
      <div class="flex">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to root_path, class: 'logo', 'aria-label': 'Return back home' do %>
            <%= image_tag 'icons/odin-icon.svg', alt: 'Odin Logo', class: 'block lg:hidden h-12 w-auto' %>
          <% end %>

          <%= render LogoComponent.new(classes: 'hidden lg:block h-12 w-auto') %>
        </div>

      </div>
      <div class="hidden md:ml-6 md:flex sm:items-center">
        <% if user_signed_in? %>
          <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
            <%= render Nav::ItemComponent.new(path: dashboard_path, text: 'Dashboard', test_id: 'nav-dashboard') %>
            <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths') %>
            <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community') %>
            <%= render Nav::ItemComponent.new(path: support_us_path, text: 'Support us', test_id: 'nav-support-us') %>
          </div>

          <%= link_to notifications_path, class: 'ml-3 bg-white dark:bg-gray-900 p-1 rounded-full text-gray-400 dark:text-gray-300 relative hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-gold-500', data: { test_id: 'navbar-notification-icon' } do %>
            <span class="sr-only">View notifications</span>
            <% if unread_notifications?(current_user) %>
                <span data-test-id="unread-notifications" class="absolute top-1 right-0.5 w-2 h-2 rounded-lg bg-gold-500"></span>
              <% end %>
            <%= inline_svg_tag 'icons/bell.svg', class: 'h-6 w-6', aria: true, title: 'Notifications icon' %>
          <% end %>
          <%= turbo_frame_tag 'theme_switcher', class: 'flex items-center justify-center' do %>
            <%= render Theme::SwitcherComponent.new(current_theme:, type: :icon_only) %>
          <% end %>
          <%= render User::ProfileDropdownComponent.new(current_user:) %>
        <% else %>
          <div class="hidden md:ml-6 md:flex sm:space-x-8">
          <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths') %>
          <%= render Nav::ItemComponent.new(path: about_path, text: 'About', test_id: 'nav-about') %>
          <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community') %>
          <%= render Nav::ItemComponent.new(path: support_us_path, text: 'Support us', test_id: 'nav-support-us') %>
          <%= render Nav::ItemComponent.new(path: sign_in_path, text: 'Sign in', test_id: 'nav-sign-in') %>
          <%= turbo_frame_tag 'theme_switcher', class: 'flex items-center justify-center w-6' do %>
            <%= render Theme::SwitcherComponent.new(current_theme:, type: :icon_only) %>
          <% end %>
          <%= link_to 'Get Started', sign_up_path, class: 'button button--primary md:px-2 md:py-2 lg:px-4 text-sm', data: { test_id: 'nav-sign-up' } %>
        </div>

        <% end %>
      </div>

      <div class="-mr-2 flex items-center md:hidden" data-controller="open-menu" data-open-menu-visibility-outlet=".off-canvas-menu">
        <button type="button" data-action="open-menu#open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:text-gray-300 dark:hover:text-gray-200 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-gold-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open mobile menu</span>
          <%= inline_svg_tag 'icons/ham-burger.svg', class: 'block h-6 w-6', aria: true, title: 'Open mobile menu button' %>
        </button>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_off_canvas_menu.html.erb
<div
  data-controller="visibility"
  data-visibility-target="content"
  data-visibility-visible-value="false"
  class="fixed inset-0 flex z-40 hidden lg:hidden off-canvas-menu"
  role="dialog"
  aria-modal="true">

  <div
    data-visibility-target="content"
    data-action="click->visibility#off"
    class="fixed inset-0 bg-gray-600 bg-opacity-75 dark:bg-black dark:bg-opacity-60 hidden"
    aria-hidden="true"
    data-transition-enter="transition-opacity ease-linear duration-200"
    data-transition-enter-start="transform opacity-0"
    data-transition-enter-end="transform opacity-100"
    data-transition-leave="transition-opacity ease-linear duration-200"
    data-transition-leave-start="transform opacity-100"
    data-transition-leave-end="transform opacity-0">
  </div>

    <div
      data-visibility-target="content"
      class="relative flex-1 flex flex-col max-w-xs w-full bg-white focus:outline-none hidden dark:bg-gray-800"
      data-transition-enter="transition ease-in-out duration-200 transform"
      data-transition-enter-start="-translate-x-full"
      data-transition-enter-end="translate-x-0"
      data-transition-leave="transition ease-in-out duration-200 transform"
      data-transition-leave-start="translate-x-0"
      data-transition-leave-end="-translate-x-full">

      <div
        data-visibility-target="content"
        class="absolute top-2 right-2 -mr-12 pt-3 hidden"
        data-transition-enter="transition ease-in-out duration-200"
        data-transition-enter-start="transform opacity-0"
        data-transition-enter-end="transform opacity-100"
        data-transition-leave="transition ease-in duration-200"
        data-transition-leave-start="transform opacity-100"
        data-transition-leave-end="transform opacity-0">
        <button type="button" data-action="click->visibility#off" class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
          <span class="sr-only">Close sidebar</span>
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <div class="flex-1 h-0 pt-3 pb-4 overflow-y-auto">
        <div class="flex-shrink-0 flex items-center px-4">
          <%= render LogoComponent.new(classes: 'h-12 w-auto') %>
        </div>
        <nav aria-label="Sidebar" class="mt-3">
          <div class="px-2 space-y-1">
            <% if user_signed_in? %>
              <%= render Nav::ItemComponent.new(path: dashboard_path, text: 'Dashboard', test_id: 'nav-dashboard', icon_path: 'icons/home.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths', icon_path: 'icons/map.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: notifications_path, text: 'Notifications', test_id: 'nav-notifications', icon_path: 'icons/bell.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: support_us_path, text: 'Support Us', test_id: 'nav-support-us', icon_path: 'icons/heart-outline.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community', icon_path: 'icons/speech-bubbles.svg', options: { mobile: true }) %>
            <% else %>
              <%= render Nav::ItemComponent.new(path: root_path, text: 'Home', test_id: 'nav-home', icon_path: 'icons/home.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths', icon_path: 'icons/map.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: about_path, text: 'About', test_id: 'nav-about', icon_path: 'icons/information.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: support_us_path, text: 'Support Us', test_id: 'nav-support-us', icon_path: 'icons/heart-outline.svg', options: { mobile: true }) %>
              <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community', icon_path: 'icons/speech-bubbles.svg', options: { mobile: true }) %>
            <% end %>
          </div>
          <hr class="border-t border-gray-200 my-4" aria-hidden="true">
          <div class="px-2 space-y-1">
            <% if user_signed_in? %>
              <%= render Nav::ItemComponent.new(path: edit_users_profile_path, text: 'Settings', test_id: 'nav-settings', icon_path: 'icons/gear.svg', options: { mobile: true }) %>
               <%= turbo_frame_tag 'theme_switcher_mobile' do %>
                <%= render Theme::SwitcherComponent.new(current_theme:, type: :mobile) %>
              <% end %>
              <%= render Nav::ItemComponent.new(path: sign_out_path, text: 'Sign out', test_id: 'nav-sign-out', icon_path: 'icons/sign-out.svg', options: { method: :delete, mobile: true }) %>
            <% else %>
              <%= render Nav::ItemComponent.new(path: sign_up_path, text: 'Get started', test_id: 'nav-sign-up', icon_path: 'icons/rocket.svg', options: { mobile: true }) %>
              <%= turbo_frame_tag 'theme_switcher_mobile' do %>
                <%= render Theme::SwitcherComponent.new(current_theme:, type: :mobile) %>
              <% end %>
              <%= render Nav::ItemComponent.new(path: sign_in_path, text: 'Sign in', test_id: 'nav-sign-in', icon_path: 'icons/sign-in.svg', options: { mobile: true }) %>
            <% end %>
          </div>
        </nav>
      </div>
    </div>

    <div class="flex-shrink-0 w-14" aria-hidden="true">
      <!-- Force sidebar to shrink to fit close icon -->
    </div>
  </div>
</div>