config/routes.rb
# rubocop:disable Lint/MissingCopEnableDirective, Metrics/BlockLength
Rails.application.routes.draw do
  match '/404' => 'errors#not_found', via: :all
  match '422' => 'errors#unprocessable_entity', via: :all
  match '500' => 'errors#internal_server_error', via: :all

  draw(:redirects)
  draw(:admin_v2)
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => 'admin/feature_flags', as: :admin_feature_flags
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
  end

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  unauthenticated do
    root 'static_pages#home'
  end

  authenticated :user do
    root to: redirect('/dashboard'), as: :authenticated_root
  end

  devise_for(
    :users,
    module: 'users',
    controllers: { passwords: 'users/password_resets' },
    path_names: { password: 'password_reset' }
  )

  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    delete '/sign_out' => 'users/sessions#destroy'
    get '/sign_up' => 'users/registrations#new'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
    resources :points, only: %i[index show create]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'team' => 'static_pages#team'
  get 'contributing' => 'static_pages#contributing'
  get 'support_us' => 'static_pages#support_us'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  namespace :guides do
    resources :installations, only: :index
    resource :community, only: :show, controller: 'community' do
      collection do
        get :before_asking
        get :how_to_ask
        get :expectations
        get :rules
      end
    end
  end

  # failure route if github information returns invalid
  get '/auth/failure' => 'users/omniauth_callbacks#failure'
  get 'dashboard' => 'users#show', as: :dashboard

  namespace :users do
    resources :paths, only: :create
    resources :progress, only: :destroy
    resource :profile, only: %i[edit update]
  end

  namespace :lessons do
    resource :preview, only: %i[show create] do
      resource :share, only: %i[create], controller: 'previews/share'
    end
  end

  namespace :courses do
    resources :progress, only: %i[show]
  end

  resources :lessons, only: :show do
    resources :project_submissions, except: :show, controller: 'lessons/project_submissions'
    resource :completion, only: %i[create destroy], controller: 'lessons/completions'
  end

  resources :project_submissions, only: :index do
    resources :flags, only: %i[new create], controller: 'project_submissions/flags'
    resource :like, only: %i[update], controller: 'project_submissions/likes'
  end

  resources :paths, only: %i[index show] do
    resources :courses, only: :show
  end

  resources :notifications, only: %i[index update]
  resource :themes, only: :update
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: %i[slugged history finders]

  belongs_to :section
  has_one :course, through: :section
  has_one :path, through: :course
  has_one :content, dependent: :destroy
  has_many :project_submissions, dependent: :destroy
  has_many :lesson_completions, dependent: :destroy
  has_many :completing_users, through: :lesson_completions, source: :user

  scope :most_recent_updated_at, -> { maximum(:updated_at) }
  scope :installation_lessons, -> { where(installation_lesson: true) }

  validates :position, presence: true

  delegate :body, to: :content

  attribute :completed, :boolean, default: false

  def complete!
    self.completed = true
  end

  def incomplete!
    self.completed = false
  end

  def import_content_from_github
    LessonContentImporter.for(self)
  end

  def display_title
    return "Project: #{title}" if is_project?

    title
  end

  private

  def slug_candidates
    [
      [course.title, title].uniq,
      [course.path_short_title, course.title, title].uniq,
      [course.path_short_title, course.title, title, SecureRandom.hex(2)].uniq
    ]
  end
end

app/controllers/lessons/completions_controller.rb
module Lessons
  class CompletionsController < ApplicationController
    before_action :authenticate_user!

    # rubocop: disable Metrics/MethodLength
    def create
      @lesson = Lesson.find(params[:lesson_id])

      lesson_completion = current_user.lesson_completions.find_or_create_by!(
        lesson: @lesson,
        lesson_identifier_uuid: @lesson.identifier_uuid,
        course: @lesson.course,
        path: @lesson.course.path,
      )

      if lesson_completion
        @lesson.complete!

        respond_to do |format|
          format.html { redirect_to @lesson }
          format.turbo_stream
        end
      else
        redirect_to @lesson, alert: 'Cannot complete lesson', status: :unprocessable_entity
      end
    end
    # rubocop: enable Metrics/MethodLength

    # rubocop: disable Metrics/MethodLength
    def destroy
      @lesson = Lesson.find(params[:lesson_id])
      lesson_completion = current_user.lesson_completions.find_by!(lesson: @lesson)

      if lesson_completion.present?
        @lesson.incomplete!
        lesson_completion.destroy

        respond_to do |format|
          format.html { redirect_to @lesson }
          format.turbo_stream { render :create }
        end
      else
        redirect_to @lesson, alert: 'Cannot uncomplete lesson', status: :unprocessable_entity
      end
    end
    # rubocop: enable Metrics/MethodLength
  end
end

app/controllers/lessons/previews/share_controller.rb
module Lessons
  module Previews
    class ShareController < ApplicationController
      def create
        @preview = LessonPreview.new(content: params[:content])

        respond_to do |format|
          if @preview.save
            format.turbo_stream
          else
            flash.now[:alert] = 'Unable to share preview'

            format.turbo_stream { render turbo_stream: turbo_stream.update('flash-messages', partial: 'shared/flash') }
          end
        end
      end
    end
  end
end

app/controllers/lessons/previews_controller.rb
module Lessons
  class PreviewsController < ApplicationController
    def show
      @preview = LessonPreview.find_or_initialize_by(id: params[:uuid])
    end

    def create
      @preview = LessonPreview.new(content: params[:markdown])

      respond_to do |format|
        format.turbo_stream
      end
    end
  end
end

app/controllers/lessons/project_submissions_controller.rb
module Lessons
  class ProjectSubmissionsController < ApplicationController
    include Sortable

    before_action :authenticate_user!
    before_action :set_lesson
    before_action :can_add_solution

    def index
      project_submissions = @lesson
        .project_submissions
        .only_public
        .sort_by_params(sort_column_for(ProjectSubmission), sort_direction)

      @pagy, @project_submissions = pagy(project_submissions.includes(:user), items: params.fetch(:limit, 15))
      mark_liked_project_submissions
    end

    def new
      @project_submission = current_user.project_submissions.new(lesson: @lesson)
    end

    def edit
      @project_submission = current_user.project_submissions.find(params[:id])
    end

    def create
      @project_submission = current_user.project_submissions.new(project_submission_params.merge(lesson: @lesson))

      respond_to do |format|
        if @project_submission.save
          @project_submission.like(current_user)

          format.html { redirect_to lesson_path(@lesson), notice: 'Project submitted' }
          format.turbo_stream
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def update
      @project_submission = current_user.project_submissions.find(params[:id])

      respond_to do |format|
        if @project_submission.update(project_submission_params)
          format.html { redirect_to lesson_path(@lesson), notice: 'Project updated' }
          format.turbo_stream
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @project_submission = current_user.project_submissions.find(params[:id])
      @project_submission.destroy

      respond_to do |format|
        format.turbo_stream
      end
    end

    private

    def mark_liked_project_submissions
      ProjectSubmissions::MarkLiked.call(
        user: current_user,
        project_submissions: @project_submissions
      )
    end

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def project_submission_params
      params.require(:project_submission).permit(
        :repo_url,
        :live_preview_url,
        :is_public,
        :lesson_id
      )
    end

    def can_add_solution
      return if @lesson.accepts_submission?

      redirect_to lesson_url(@lesson), alert: 'This project does not accept submissions'
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_cache_control_header_to_no_store

  def show
    @lesson = Lesson.find(params[:id])

    if user_signed_in?
      @project_submission = current_user.project_submissions.find_by(lesson: @lesson)
      Courses::MarkCompletedLessons.call(user: current_user, lessons: Array(@lesson))
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def github_edit_url(lesson)
    github_link("curriculum/edit/main#{lesson.github_path}")
  end

  def github_report_url(lesson)
    params = {
      labels: 'Status: Needs Triage',
      template: 'suggestion.yaml',
      title: "#{lesson.title}: <Short description of your suggestion>",
      'lesson-link': lesson_url(lesson)
    }

    github_link("curriculum/issues/new?#{params.to_query}")
  end
end

app/views/lessons/_header.html.erb
<header class="mb-16 grid grid-cols-12">
  <div class="flex space-y-4 items-center flex-col col-span-full justify-center xl:space-y-0 xl:space-x-4 xl:flex-row xl:justify-start xl:col-start-2">
    <%= render Course::BadgeComponent.new(course: lesson.course, options: {show_badge: true }) %>

    <div class="text-center xl:text-left">
      <h1 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 min-w-full" data-test-id="lesson-title-header">
        <%= lesson.display_title %>
      </h1>

      <%= link_to path_course_url(lesson.course.path, lesson.course), class: 'no-underline' do %>
        <h2 class="min-w-full text-lg text-gray-500 dark:text-gray-400" data-test-id="course-title-header">
          <%= lesson.course.title %> Course
        </h2>
      <% end %>
    </div>
  </div>
</header>

app/views/lessons/_lesson_buttons.html.erb
<div class="flex flex-col justify-between max-w-sm mx-auto space-y-6 md:max-w-full md:space-y-0 md:flex-row md:space-x-7">
  <%= link_to path_course_path(course.path, course), class: 'button button--secondary px-4 py-2 font-medium', data: { test_id: 'view-course-btn' } do %>
    <%= inline_svg_tag 'icons/academic-cap.svg', class: 'h-8 w-8 pr-2', aria: true, title: 'View course', desc: 'Go to course page' %>
    View Course
  <% end %>

  <% if user_signed_in? %>
    <%= render Complete::ButtonComponent.new(lesson:) %>
  <% else %>
    <%= link_to(
          'Sign in to track progress',
          sign_in_path,
          class: 'button button--primary',
          data: { test_id: 'sign_in_button' }
        ) %>
  <% end %>

  <% if course.next_lesson(lesson).present? %>
    <%= link_to lesson_path(course.next_lesson(lesson)), class: 'button button--secondary px-4 py-2 font-medium', data: { test_id: 'next-lesson-btn' } do %>
      <%= inline_svg_tag 'icons/arrow-right-circle.svg', class: 'h-8 w-8 pr-2', aria: true, title: 'Next lesson', desc: 'Go to next lesson' %>
      Next Lesson
    <% end %>
  <% elsif lesson.choose_path_lesson? %>
    <%= link_to paths_url, class: 'button button--secondary px-4 font-medium', data: { test_id: 'choose-path-lesson-btn' } do %>
      <%= inline_svg_tag 'icons/map.svg', class: 'h-8 w-8 pr-2', aria: true, title: 'Choose path', desc: 'Go to paths page' %>
      Choose Path
    <% end %>
  <% end %>
</div>

app/views/lessons/_project_solution.html.erb
<div id="project-solution" class="mb-8 text-left scroll-mt-24">

  <header class="flex flex-col space-y-4 sm:space-y-0 items-center sm:flex-row justify-between w-full pb-8">
    <h3 class="text-2xl font-medium text-gray-900 dark:text-gray-200">Your solution</h3>

    <%= link_to 'View community solutions', lesson_project_submissions_path(lesson), class: 'button button--secondary rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900' %>
  </header>

  <div class="mx-auto">
    <div class="relative block w-full rounded-lg bg-gray-50 dark:bg-gray-700/50 group single-item" data-test-id="current-user-solution">
      <%= render ProjectSubmissions::UserSolutionComponent.new(project_submission:) %>

      <%= link_to new_lesson_project_submission_path(lesson), class: 'p-6 relative hidden only:block group block w-full hover:bg-gray-100 hover:dark:bg-gray-700 rounded-lg text-center focus:outline-none', data: { turbo_frame: 'modal', test_id: 'add_submission_btn' }  do %>
        <%= inline_svg_tag 'icons/plus-circle.svg', class: 'mx-auto h-12 w-12 text-gray-400 group-hover:text-gray-500 group-hover:dark:text-gray-300', aria: true, title: 'Submit your solution' %>
        <span class="mt-2 block text-sm font-semibold text-gray-900 dark:text-gray-300">Submit your solution</span>
      <% end %>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<%= title(@lesson.display_title) %>

<div class="bg-white dark:bg-gray-900">
  <div class="page-container pb-10">

    <%= render 'lessons/header', lesson: @lesson %>

    <main class="grid grid-cols-12 gap-x-6" data-controller="lesson-toc" data-lesson-toc-item-classes-value="no-underline hover:text-gray-800 text-sm dark:hover:text-gray-300">
      <article class="col-span-full xl:col-span-7 xl:col-start-2">
        <%= render ContentContainerComponent.new(classes: 'xl:mx-0 pb-6', data_attributes: { lesson_toc_target: 'lessonContent' }) do |component| %>
          <%= @lesson.body.html_safe %>

          <% component.with_footer do %>
            <%= link_to github_edit_url(@lesson), target: :_blank, rel: 'noreferrer noopener', class: 'text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 pr-5 text-sm' do %>
              <%= inline_svg_tag 'icons/github.svg', class: 'h-4 w-4 mr-1 inline', aria: true, title: 'Improve on GitHub', desc: 'Github logo icon' %>
              <span class="underline hover:no-underline">Improve on GitHub</span>
            <% end %>

            <%= link_to github_report_url(@lesson), target: :_blank, rel: 'noreferrer noopener', class: 'inline-flex items-center underline hover:no-underline text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300 pr-5 text-sm' do %>
              <%= inline_svg_tag 'icons/flag.svg', class: 'h-4 w-4 mr-1 inline', aria: true, title: 'Report an issue', desc: 'Report icon' %>
              <span>Report an issue</span>
            <% end %>
          <% end %>
        <% end %>

        <% if user_signed_in? && @lesson.accepts_submission? %>
          <div class="py-10 border-t border-gray-100 dark:border-white/5">
            <div class="max-w-2xl mx-auto xl:max-w-full border border-gray dark:border-white/5 rounded-lg p-4 dark:bg-gray-800">
              <%= render 'lessons/project_solution', lesson: @lesson, project_submission: @project_submission %>
            </div>
          </div>
        <% end %>

        <div class="pt-10 border-t border-gray-100 dark:border-white/5">
          <%= render 'lesson_buttons', lesson: @lesson, course: @lesson.course, user: @user %>
        </div>
      </article>

      <aside class="col-span-3 col-start-10 justify-self-end hidden xl:block">
        <div class="sticky top-12 pb-20">
          <h4 class="text-md pb-4 text-gray-700 dark:text-gray-300">Lesson contents</h4>
          <ul class="flex flex-col text-gray-500 dark:text-gray-400" data-lesson-toc-target="toc"></ul>
        </div>
      </aside>
    </main>
  </div>
</div>